import type { Lang, TextPack } from "./home.types";

export const HOME_TEXT: Record<Lang, TextPack> = {
  en: {
    title: "Rickshaw Tracking System",
    heroBadge: "Simple transport system",
    heroTitle: "Manage rickshaws easily in your area",
    heroHighlight: "Fast and simple",
    heroDesc:
      "A simple system for drivers, garage owners, and admins to manage trips, track vehicles, and reduce confusion in daily work.",
    primary: "Get Started",
    secondary: "Learn More",
    chooseAction: "Choose an option",
    chooseRole: "Select your role",
    login: "Login",
    register: "Register",
    driver: "Driver",
    owner: "Garage Owner",
    admin: "Admin",
    back: "Back",
    infoTitle: "About this system",
    infoDesc:
      "Built for local rickshaw operations in Bangladesh. Designed for non-technical users with minimal training.",
    feature1Title: "Track location",
    feature1Desc: "See where rickshaws are working in your area.",
    feature2Title: "Busy area view",
    feature2Desc: "Understand roads with high demand.",
    feature3Title: "Easy management",
    feature3Desc: "Assign and manage rickshaws simply.",
    feature4Title: "Safety monitoring",
    feature4Desc: "Detect missing or inactive rickshaws.",
    stat1: "Active Rickshaws",
    stat2: "Areas Covered",
    stat3: "Alerts",
    stat4: "Efficiency",
    footer: "Built for real-world simplicity",
    toggleLang: "বাংলা",
    textSize: "A+",
  },
  bn: {
    title: "রিকশা ট্র্যাকিং সিস্টেম",
    heroBadge: "সহজ পরিবহন ব্যবস্থা",
    heroTitle: "আপনার এলাকার রিকশা সহজে পরিচালনা করুন",
    heroHighlight: "দ্রুত ও সহজ",
    heroDesc:
      "চালক, গ্যারেজ মালিক এবং অ্যাডমিনদের জন্য একটি সহজ সিস্টেম, যা ট্রিপ, রিকশা ট্র্যাকিং এবং দৈনন্দিন কাজ সহজ করে।",
    primary: "শুরু করুন",
    secondary: "আরও জানুন",
    chooseAction: "একটি অপশন বেছে নিন",
    chooseRole: "আপনার ভূমিকা নির্বাচন করুন",
    login: "লগইন",
    register: "রেজিস্ট্রেশন",
    driver: "চালক",
    owner: "গ্যারেজ মালিক",
    admin: "অ্যাডমিন",
    back: "ফিরে যান",
    infoTitle: "এই সিস্টেম সম্পর্কে",
    infoDesc:
      "বাংলাদেশের স্থানীয় রিকশা ব্যবস্থাপনার জন্য তৈরি। কম টেকনিক্যাল জ্ঞান থাকলেও ব্যবহার করা সহজ।",
    feature1Title: "লোকেশন ট্র্যাক",
    feature1Desc: "রিকশা কোথায় কাজ করছে দেখুন।",
    feature2Title: "ব্যস্ত এলাকার ভিউ",
    feature2Desc: "কোন রাস্তায় চাহিদা বেশি বুঝুন।",
    feature3Title: "সহজ ব্যবস্থাপনা",
    feature3Desc: "সহজে রিকশা বরাদ্দ ও পরিচালনা করুন।",
    feature4Title: "নিরাপত্তা পর্যবেক্ষণ",
    feature4Desc: "অনুপস্থিত বা নিষ্ক্রিয় রিকশা শনাক্ত করুন।",
    stat1: "সক্রিয় রিকশা",
    stat2: "কভার করা এলাকা",
    stat3: "অ্যালার্ট",
    stat4: "দক্ষতা",
    footer: "বাস্তব ব্যবহারের জন্য সহজভাবে তৈরি",
    toggleLang: "EN",
    textSize: "A+",
  },
};
